# Generated by Django 5.2 on 2025-04-23 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0003_checklist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
