# Generated by Django 5.2 on 2025-04-24 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0004_checklistitem_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='share_uuid',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
