# Generated by Django 5.2 on 2025-04-24 05:47

from django.db import migrations
import uuid

def generate_share_uuids(apps, schema_editor):
    Checklist = apps.get_model("checklists", "Checklist")
    for checklist in Checklist.objects.all():
        checklist.share_uuid = uuid.uuid4()
        checklist.save()

class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0005_checklist_share_uuid'),
    ]

    operations = [
	    migrations.RunPython(generate_share_uuids),
    ]
