# Generated by Django 5.2 on 2025-04-24 05:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0006_auto_20250424_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='share_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
